import type { NextPage } from 'next';
import { Session } from 'next-auth';
import { getSession } from 'next-auth/client';
import Head from 'next/head';
import React from 'react';
import Feed from '../components/Feed';
import Header from '../components/Header';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';

const Home: NextPage<{ session: Session | null }> = ({ session }) => {
  if (!session) return <Login />;

  return (
    <div className="h-screen overflow-hidden bg-gray-100">
      <Head>
        <title>FacebooC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Widget */}
      </main>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  // Get the user
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}

export default Home;
